version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

  server:
      build: .
      command: python app/main.py
      volumes:
        - .:/app
      ports:
        - 8080:8080
      env_file:
      - .env
      environment:
      - WEB_SOURCE=${SOURCE}
      depends_on:
        - postgres

  get_data:
      build: .
      command: curl server:8080/get_data
      depends_on:
        - server

  print_data:
      build: .
      command: curl server:8080/print_data
      depends_on:
        - server
